---
version: "3.3"

services:

  musicbot_alpha:
    restart: always
    build: &buildinstructions
      context: ./MusicBot
      dockerfile: ../Dockerfile
    volumes:
      - ./config_alpha.txt:/MusicBot/config.txt
