---
version: "3.3"

services:

  musicbot_alpha:
    restart: always
    build: &buildinstructions
      context: ./MusicBot
      dockerfile: ../Dockerfile
    volumes:
      - ./config_alpha.txt:/MusicBot/config.txt

  musicbot_beta:
    restart: always
    build: *buildinstructions
    volumes:
      - ./config_beta.txt:/MusicBot/config.txt

  musicbot_gamma:
    restart: always
    build: *buildinstructions
    volumes:
      - ./config_gamma.txt:/MusicBot/config.txt
